# Generated by Django 4.1.1 on 2022-10-05 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temperature', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='citytemperature',
            unique_together={('city', 'date')},
        ),
    ]
